matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: osx
          osx_image: xcode8
language: r
pandoc_version: 1.17.2
cache: [packages, pip]
before_install:
    - pip install -U pip
install:
    - pip install -U pandocfilters
    - sudo tlmgr install latexmk
    - sudo tlmgr install physics
    - sudo tlmgr install cancel
    - sudo tlmgr install siunitx #macOS only
    - sudo tlmgr install placeins #macOS only
script:
    - make
    - make pandoc
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "README.pdf"
    - "workbook-7a.pdf"
    - "workbook-8a.pdf"
    - "workbook-master.pdf"
    - "7a-workbook.pdf"
    - "8a-workbook.pdf"
    - "master-workbook.pdf"
  skip_cleanup: true
  on:
    tags: true
