matrix:
    include:
        # Linux container, R
        - os: linux
          language: r
          install:
              - pip install --user pandocfilters
              - tlmgr install latexmk physics cancel fourier utopia
          cache:
          - packages
          - pip
        # Linux VM, R
        - os: linux
          sudo: required
          dist: trusty
          language: r
          install:
              - pip install -U pip pandocfilters
              - tlmgr install latexmk physics cancel fourier utopia
          cache:
          - packages
          - pip
        # Linux VM, Python
        - os: linux
          sudo: required
          dist: trusty
          language: python
          before_install:
              - sudo apt-get -qq update
          addons:
            apt:
              packages:
              - texlive-full
          install:
              - pip install -U pip pandocfilters
              - wget https://github.com/jgm/pandoc/releases/download/2.3.1/pandoc-2.3.1-1-amd64.deb && sudo dpkg -i pandoc-2.3.1-1-amd64.deb
          cache:
          - pip
        # macOS, R
        - os: osx
          language: r
          install:
              - pip install -U pip pandocfilters
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins
          cache:
          - packages
          - pip
        # macOS generic
        - os: osx
          language: generic
          before_install:
              - brew update
              - brew install pandoc
              - brew cask install basictex
          install:
              - pip install -U pip pandocfilters
              - export PATH="/Library/TeX/texbin:$PATH" && sudo tlmgr update --self
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins
          cache:
          - pip
        # macOS xcode10, R
        - os: osx
          osx_image: xcode10
          language: r
          install:
              - pip install -U pip pandocfilters
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins
          cache:
          - packages
          - pip
        # macOS xcode10, generic
        - os: osx
          osx_image: xcode10
          language: generic
          before_install:
              - brew update
              - brew install pandoc
              - brew cask install basictex
          install:
              - pip install -U pip pandocfilters
              - export PATH="/Library/TeX/texbin:$PATH" && sudo tlmgr update --self
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins
          cache:
          - pip
before_script:
    - git submodule update --init --recursive --remote
script:
    - make -j3 travis
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "workbook-7A.pdf"
    - "workbook-8A.pdf"
    - "workbook-Master.pdf"
    - "workbook-7A.epub"
    - "workbook-8A.epub"
    - "workbook-Master.epub"
  skip_cleanup: true
  on:
    tags: true
