language: r
cache: [packages, pip]
sudo: required
dist: trusty
pandoc_version: 1.17.2
before_install:
    - pip install -U pip
    - tlmgr update --self
install:
    - pip install -U pandocfilters
    - tlmgr install latexmk
    - tlmgr install physics
    - tlmgr install cancel
    - tlmgr install amsfonts
    - tlmgr install amsmath
    - tlmgr install lm
    - tlmgr install ifxetex
    - tlmgr install ifluatex
    - tlmgr install eurosym
    - tlmgr install listings
    - tlmgr install fancyvrb
    - # tlmgr install longtable
    - tlmgr install booktabs
    - # tlmgr install graphicx
    - # tlmgr install grffile
    - tlmgr install hyperref
    - tlmgr install ulem
    - tlmgr install geometry
    - tlmgr install setspace
    - tlmgr install babel
script:
    - make
    - make pandoc
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "README.pdf"
    - "workbook-7a.pdf"
    - "workbook-8a.pdf"
    - "workbook-master.pdf"
    - "7a-workbook.pdf"
    - "8a-workbook.pdf"
    - "master-workbook.pdf"
  skip_cleanup: true
  on:
    tags: true
