matrix:
    include:
        - os: linux
          sudo: false
          language: r
          pandoc_version: 1.18
          before_install:
              - pip install --user pandocfilters
          install:
              - tlmgr install latexmk physics cancel fourier utopia
          cache:
          - packages
          - pip
        - os: linux
          sudo: required
          dist: trusty
          language: r
          pandoc_version: 1.18
          before_install:
              - pip install -U pip pandocfilters
          install:
              - tlmgr install latexmk physics cancel fourier utopia
          cache:
          - packages
          - pip
        - os: linux
          sudo: required
          dist: trusty
          language: python
          before_install:
              - sudo apt-get -qq update
              - pip install -U pip
          addons:
            apt:
              packages:
              - texlive-full
          install:
              - wget https://github.com/jgm/pandoc/releases/download/1.18/pandoc-1.18-1-amd64.deb && sudo dpkg -i pandoc-1.18-1-amd64.deb
              - pip install pandocfilters
          cache:
          - pip
        - os: osx
          osx_image: xcode8
          language: r
          pandoc_version: 1.18
          before_install:
              - pip install -U pip pandocfilters
          install:
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins
          cache:
          - packages
          - pip
script:
    - make -j4 travis
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "workbook-7A.pdf"
    - "workbook-8A.pdf"
    - "workbook-Master.pdf"
    - "workbook-7A.epub"
    - "workbook-8A.epub"
    - "workbook-Master.epub"
  skip_cleanup: true
  on:
    tags: true
